/* For any item that has a colour_combat tag, set it to 0 if that item ever gets its own combat sprites. */
function initUnderLower() {
	setup.clothes.under_lower = [
		{
			index: 0,
			name: "naked",
			name_cap: "Naked",
			name_simple: "naked",
			variable: "naked",
			integrity: 0,
			integrity_max: 0,
			fabric_strength: 0,
			reveal: 1000,
			rearresize: 0,
			word: "n",
			one_piece: 0,
			state: 0,
			state_base: 0,
			plural: 0,
			colour: 0,
			colour_options: [],
			exposed: 1,
			exposed_base: 1,
			vagina_exposed: 1,
			vagina_exposed_base: 1,
			anus_exposed: 1,
			anus_exposed_base: 1,
			type: ["naked"],
			anal_shield: 0,
			set: "under_lower",
			gender: "n",
			warmth: 0,
			cost: 0,
			description: "naked",
			shop: [],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			penis_img: 0,
			high_img: 0,
			cursed: 0,
			location: 0,
			iconFile: 0,
			accIcon: 0,
			mainImage: 0,
		},

		{
			index: 1,
			name: "plain panties",
			name_cap: "Plain panties",
			name_simple: "panties",
			variable: "plainpanties",
			integrity: 100,
			integrity_max: 100,
			fabric_strength: 15,
			reveal: 400,
			rearresize: 0,
			word: "n",
			one_piece: 0,
			state: "waist",
			state_base: "waist",
			plural: 1,
			colour: 0,
			colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "pale tangerine", "teal", "pale white", "pale yellow", "custom"],
			colour_sidebar: 1,
			exposed: 0,
			exposed_base: 0,
			vagina_exposed: 0,
			vagina_exposed_base: 0,
			anus_exposed: 0,
			anus_exposed_base: 0,
			type: ["normal"],
			anal_shield: 0,
			set: "under_lower",
			gender: "f",
			femininity: 300,
			warmth: 5,
			cost: 500,
			description: "No-nonsense.",
			shop: ["clothing", "school", "adult"],
			shopGroup: "plainpanties",
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			penis_img: 1,
			high_img: 0,
			cursed: 0,
			location: 0,
			iconFile: "plain_panties.png",
			accIcon: 0,
		},

		{
			index: 2,
			name: "bikini bottoms",
			name_cap: "Bikini bottoms",
			name_simple: "bikini bottoms",
			variable: "bikini",
			integrity: 20,
			integrity_max: 20,
			fabric_strength: 20,
			reveal: 700,
			rearresize: 0,
			word: "n",
			one_piece: 0,
			state: "waist",
			state_base: "waist",
			plural: 1,
			colour: 0,
			colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "tangerine", "teal", "white", "yellow", "custom"],
			colour_sidebar: 1,
			exposed: 0,
			exposed_base: 0,
			vagina_exposed: 0,
			vagina_exposed_base: 0,
			anus_exposed: 0,
			anus_exposed_base: 0,
			type: ["swim", "tanLines"],
			anal_shield: 0,
			set: "under_lower",
			gender: "f",
			femininity: 300,
			warmth: 5,
			cost: 2000,
			description: "Revealing swimwear.",
			shop: ["clothing"],
			shopGroup: "bikinibottom",
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			penis_img: 1,
			high_img: 0,
			cursed: 0,
			location: 0,
			iconFile: "bikini_bottoms.png",
			accIcon: 0,
		},

		{
			index: 3,
			name: "lace panties",
			name_cap: "Lace panties",
			name_simple: "panties",
			variable: "lacepanties",
			integrity: 60,
			integrity_max: 60,
			fabric_strength: 15,
			reveal: 600,
			rearresize: 0,
			word: "n",
			one_piece: 0,
			state: "waist",
			state_base: "waist",
			plural: 1,
			colour: 0,
			colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "pale tangerine", "teal", "pale white", "pale yellow", "custom"],
			colour_sidebar: 1,
			exposed: 0,
			exposed_base: 0,
			vagina_exposed: 0,
			vagina_exposed_base: 0,
			anus_exposed: 0,
			anus_exposed_base: 0,
			type: ["normal"],
			anal_shield: 0,
			set: "under_lower",
			gender: "f",
			femininity: 300,
			warmth: 5,
			cost: 1500,
			description: "Fashionable and sexy.",
			shop: ["clothing", "adult"],
			shopGroup: "lacepanties",
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			penis_img: 0,
			high_img: 0,
			cursed: 0,
			location: 0,
			iconFile: "lace_panties.png",
			accIcon: 0,
		},

		{
			index: 4,
			name: "briefs",
			name_cap: "Briefs",
			name_simple: "undies",
			variable: "briefs",
			integrity: 100,
			integrity_max: 100,
			fabric_strength: 15,
			reveal: 400,
			rearresize: 0,
			word: "n",
			one_piece: 0,
			state: "waist",
			state_base: "waist",
			plural: 1,
			colour: 0,
			colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "pale tangerine", "teal", "pale white", "pale yellow", "custom"],
			colour_sidebar: 1,
			exposed: 0,
			exposed_base: 0,
			vagina_exposed: 0,
			vagina_exposed_base: 0,
			anus_exposed: 0,
			anus_exposed_base: 0,
			no_aside: 1,
			type: ["normal"],
			anal_shield: 0,
			set: "under_lower",
			gender: "m",
			femininity: -300,
			warmth: 5,
			cost: 500,
			description: "Snug.",
			shop: ["clothing", "school"],
			shopGroup: "briefs",
			accessory: 1,
			accessory_colour: 0,
			accessory_colour_options: [],
			accessory_colour_combat: "white",
			penis_img: 0,
			high_img: 0,
			cursed: 0,
			location: 0,
			iconFile: "briefs.png",
			accIcon: 0,
		},

		{
			index: 5,
			name: "chastity belt",
			name_cap: "Chastity belt",
			name_simple: "chastity belt",
			variable: "chastitybelt",
			integrity: 2000,
			integrity_max: 2000,
			fabric_strength: 15,
			reveal: 1000,
			rearresize: 0,
			word: "a",
			one_piece: 0,
			state: "waist",
			state_base: "waist",
			plural: 1,
			colour: 0,
			colour_options: [],
			colour_combat: "black",
			exposed: 0,
			exposed_base: 0,
			vagina_exposed: 0,
			vagina_exposed_base: 0,
			anus_exposed: 1,
			anus_exposed_base: 1,
			type: ["chastity", "swim", "school"],
			anal_shield: 0,
			set: "under_lower",
			gender: "n",
			femininity: 500,
			warmth: 0,
			cost: 0,
			description: "Restrictive.",
			shop: [],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			penis_img: 0,
			high_img: 0,
			cursed: 1,
			location: 0,
			iconFile: 0,
			accIcon: 0,
		},

		{
			index: 6,
			name: "school swimsuit bottom",
			name_cap: "School swimsuit bottom",
			name_simple: "swimsuit",
			variable: "schoolswimsuit",
			integrity: 40,
			integrity_max: 40,
			fabric_strength: 20,
			reveal: 600,
			rearresize: 0,
			word: "a",
			one_piece: 1,
			state: "waist",
			state_base: "waist",
			plural: 0,
			colour: 0,
			colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "tangerine", "teal", "white", "yellow", "custom"],
			colour_sidebar: 1,
			exposed: 0,
			exposed_base: 0,
			vagina_exposed: 0,
			vagina_exposed_base: 0,
			anus_exposed: 0,
			anus_exposed_base: 0,
			type: ["swim", "school", "tanLines"],
			anal_shield: 0,
			set: "school swimsuit",
			warmth: 5,
			gender: "f",
			femininity: 300,
			cost: 0,
			description: "Proper school swimwear.",
			shop: ["clothing", "school"],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			penis_img: 1,
			high_img: 0,
			cursed: 0,
			location: 0,
			iconFile: 0,
			accIcon: 0,
			outfitSecondary: ["under_upper", "school swimsuit"],
		},

		{
			index: 7,
			name: "school swim shorts",
			name_cap: "School swim shorts",
			name_simple: "swim shorts",
			variable: "schoolswimshorts",
			integrity: 40,
			integrity_max: 40,
			fabric_strength: 20,
			reveal: 600,
			rearresize: 0,
			word: "n",
			one_piece: 0,
			state: "waist",
			state_base: "waist",
			plural: 1,
			colour: 0,
			colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "tangerine", "teal", "white", "yellow", "custom"],
			colour_sidebar: 1,
			exposed: 0,
			exposed_base: 0,
			vagina_exposed: 0,
			vagina_exposed_base: 0,
			anus_exposed: 0,
			anus_exposed_base: 0,
			no_aside: 1,
			type: ["swim", "school", "tanLines"],
			anal_shield: 0,
			set: "under_lower",
			gender: "m",
			femininity: -300,
			warmth: 20,
			cost: 2000,
			description: "Proper school swimwear.",
			shop: ["clothing", "school"],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			penis_img: 0,
			high_img: 0,
			cursed: 0,
			location: 0,
			iconFile: "school_swim_shorts.png",
			accIcon: 0,
		},

		{
			index: 8,
			name: "leotard bottom",
			name_cap: "Leotard bottom",
			name_simple: "leotard",
			variable: "leotard",
			integrity: 100,
			integrity_max: 100,
			fabric_strength: 20,
			reveal: 600,
			rearresize: 0,
			word: "a",
			one_piece: 1,
			state: "waist",
			state_base: "waist",
			plural: 0,
			colour: 0,
			colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "tangerine", "teal", "white", "yellow", "custom"],
			colour_sidebar: 1,
			colour_combat: 0,
			exposed: 0,
			exposed_base: 0,
			vagina_exposed: 0,
			vagina_exposed_base: 0,
			anus_exposed: 0,
			anus_exposed_base: 0,
			no_aside: 1,
			type: ["dance", "athletic"],
			anal_shield: 0,
			set: "leotard",
			gender: "n",
			warmth: 20,
			cost: 0,
			description: "Form fitting.",
			shop: ["clothing", "adult"],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			penis_img: 1,
			high_img: 0,
			cursed: 0,
			location: 0,
			iconFile: 0,
			accIcon: 0,
			outfitSecondary: ["under_upper", "leotard"],
		},

		{
			index: 9,
			name: "unitard bottom",
			name_cap: "Unitard bottom",
			name_simple: "leotard",
			variable: "unitard",
			oldVariable: [{ name: "full body leotard bottom", variable: "leotardfull" }],
			integrity: 140,
			integrity_max: 140,
			fabric_strength: 20,
			reveal: 400,
			rearresize: 0,
			word: "a",
			one_piece: 1,
			state: "waist",
			state_base: "waist",
			plural: 0,
			colour: 0,
			colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "tangerine", "teal", "white", "yellow", "custom"],
			colour_sidebar: 1,
			colour_combat: 0,
			exposed: 0,
			exposed_base: 0,
			vagina_exposed: 0,
			vagina_exposed_base: 0,
			anus_exposed: 0,
			anus_exposed_base: 0,
			no_aside: 1,
			type: ["dance", "athletic"],
			anal_shield: 0,
			set: "unitard",
			gender: "n",
			warmth: 40,
			cost: 0,
			description: "Form fitting. Covers your legs.",
			shop: ["clothing", "adult"],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			penis_img: 1,
			high_img: 0,
			cursed: 0,
			location: 0,
			iconFile: 0,
			accIcon: 0,
			outfitSecondary: ["under_upper", "unitard"],
		},

		{
			index: 10,
			name: "skimpy leotard bottom",
			name_cap: "Skimpy leotard bottom",
			name_simple: "leotard",
			variable: "leotardskimpy",
			integrity: 80,
			integrity_max: 80,
			fabric_strength: 20,
			reveal: 600,
			rearresize: 0,
			word: "a",
			one_piece: 1,
			state: "waist",
			state_base: "waist",
			plural: 0,
			colour: 0,
			colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "tangerine", "teal", "white", "yellow", "custom"],
			colour_sidebar: 1,
			colour_combat: 0,
			exposed: 0,
			exposed_base: 0,
			vagina_exposed: 0,
			vagina_exposed_base: 0,
			anus_exposed: 0,
			anus_exposed_base: 0,
			type: ["dance", "athletic"],
			anal_shield: 0,
			set: "skimpy leotard",
			gender: "n",
			warmth: 10,
			cost: 0,
			description: "Form fitting. Shows off your thighs.",
			shop: ["clothing", "adult"],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			penis_img: 1,
			high_img: 0,
			cursed: 0,
			location: 0,
			iconFile: 0,
			accIcon: 0,
			outfitSecondary: ["under_upper", "skimpy leotard"],
		},

		{
			index: 11,
			name: "foreign school swimsuit bottom",
			name_cap: "Foreign school swimsuit bottom",
			name_simple: "swimsuit",
			variable: "schoolswimsuitj",
			integrity: 40,
			integrity_max: 40,
			fabric_strength: 20,
			reveal: 600,
			rearresize: 0,
			word: "a",
			one_piece: 1,
			state: "waist",
			state_base: "waist",
			plural: 0,
			colour: 0,
			colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "tangerine", "teal", "white", "yellow", "custom"],
			colour_sidebar: 1,
			exposed: 0,
			exposed_base: 0,
			vagina_exposed: 0,
			vagina_exposed_base: 0,
			anus_exposed: 0,
			anus_exposed_base: 0,
			type: ["swim", "school", "tanLines"],
			anal_shield: 0,
			set: "foreign school swimsuit",
			gender: "f",
			femininity: 300,
			warmth: 5,
			cost: 0,
			description: "Official uniform swimsuit for the local school, but in a style popular in a foreign country.",
			shop: ["clothing", "school"],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			penis_img: 1,
			high_img: 0,
			cursed: 0,
			location: 0,
			iconFile: 0,
			accIcon: 0,
			outfitSecondary: ["under_upper", "foreign school swimsuit"],
		},

		{
			index: 12,
			name: "swimsuit bottom",
			name_cap: "Swimsuit bottom",
			name_simple: "swimsuit",
			variable: "swimsuit",
			integrity: 60,
			integrity_max: 60,
			fabric_strength: 20,
			reveal: 700,
			rearresize: 0,
			word: "a",
			one_piece: 1,
			state: "waist",
			state_base: "waist",
			plural: 0,
			colour: 0,
			colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "tangerine", "teal", "white", "yellow", "custom"],
			colour_sidebar: 1,
			exposed: 0,
			exposed_base: 0,
			vagina_exposed: 0,
			vagina_exposed_base: 0,
			anus_exposed: 0,
			anus_exposed_base: 0,
			type: ["swim"],
			anal_shield: 0,
			set: "swimsuit",
			gender: "f",
			femininity: 300,
			warmth: 5,
			cost: 0,
			description: "Sexy.",
			shop: ["clothing"],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			penis_img: 1,
			high_img: 0,
			cursed: 0,
			location: 0,
			iconFile: 0,
			accIcon: 0,
			outfitSecondary: ["under_upper", "swimsuit"],
		},

		{
			index: 13,
			name: "bunny leotard bottom",
			name_cap: "Bunny leotard bottom",
			name_simple: "leotard",
			variable: "leotardbunny",
			integrity: 120,
			integrity_max: 120,
			fabric_strength: 20,
			reveal: 800,
			rearresize: 0,
			word: "a",
			one_piece: 1,
			state: "waist",
			state_base: "waist",
			plural: 0,
			colour: 0,
			colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "white", "yellow", "tan", "fleshy"],
			colour_sidebar: 1,
			colour_combat: 0,
			exposed: 0,
			exposed_base: 0,
			vagina_exposed: 0,
			vagina_exposed_base: 0,
			anus_exposed: 0,
			anus_exposed_base: 0,
			type: ["costume", "serving", "dance"],
			anal_shield: 0,
			set: "leotardbunny",
			gender: "f",
			femininity: 300,
			warmth: 5,
			cost: 0,
			description: "Waitress attire. Tougher than it looks. Part of a bunny outfit, and has a tufty white tail on the back to prove it.",
			shop: ["adult"],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			penis_img: 1,
			high_img: 0,
			cursed: 0,
			location: 0,
			iconFile: 0,
			accIcon: 0,
			outfitSecondary: ["under_upper", "bunny leotard"],
		},

		{
			index: 14,
			name: "boyshorts",
			name_cap: "Boyshorts",
			name_simple: "undies",
			variable: "boyshorts",
			integrity: 120,
			integrity_max: 120,
			fabric_strength: 20,
			reveal: 300,
			rearresize: 0,
			word: "n",
			one_piece: 0,
			state: "waist",
			state_base: "waist",
			plural: 1,
			colour: 0,
			colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "pale tangerine", "teal", "pale white", "pale yellow", "custom"],
			colour_sidebar: 1,
			exposed: 0,
			exposed_base: 0,
			vagina_exposed: 0,
			vagina_exposed_base: 0,
			anus_exposed: 0,
			anus_exposed_base: 0,
			no_aside: 1,
			type: ["normal"],
			anal_shield: 0,
			set: "under_lower",
			gender: "f",
			femininity: 300,
			warmth: 20,
			cost: 1000,
			description: "Cute and comfy.",
			shop: ["clothing"],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			penis_img: 1,
			high_img: 0,
			cursed: 0,
			location: 0,
			iconFile: "boyshorts.png",
			accIcon: 0,
		},

		{
			index: 15,
			name: "catgirl panties",
			name_cap: "Catgirl panties",
			name_simple: "panties",
			variable: "catgirlpanties",
			integrity: 100,
			integrity_max: 100,
			fabric_strength: 20,
			reveal: 500,
			rearresize: 0,
			word: "n",
			one_piece: 0,
			state: "waist",
			state_base: "waist",
			plural: 1,
			colour: 0,
			colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "tangerine", "teal", "white", "yellow", "custom"],
			colour_sidebar: 1,
			exposed: 0,
			exposed_base: 0,
			vagina_exposed: 0,
			vagina_exposed_base: 0,
			anus_exposed: 0,
			anus_exposed_base: 0,
			type: ["costume", "serving"],
			anal_shield: 0,
			set: "under_lower",
			gender: "f",
			femininity: 300,
			warmth: 5,
			cost: 3000,
			description: "For when mundane panties aren't cute enough.",
			shop: ["clothing", "adult"],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			penis_img: 1,
			high_img: 0,
			cursed: 0,
			location: 0,
			iconFile: "catgirl_panties.png",
			accIcon: 0,
		},

		{
			index: 16,
			name: "G-string",
			name_cap: "G-string",
			name_simple: "g-string",
			variable: "gstring",
			integrity: 40,
			integrity_max: 40,
			fabric_strength: 20,
			reveal: 900,
			rearresize: 0,
			word: "a",
			one_piece: 0,
			state: "waist",
			state_base: "waist",
			plural: 0,
			colour: 0,
			colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "pale tangerine", "teal", "pale white", "pale yellow", "custom"],
			colour_sidebar: 1,
			exposed: 0,
			exposed_base: 0,
			vagina_exposed: 0,
			vagina_exposed_base: 0,
			anus_exposed: 1,
			anus_exposed_base: 1,
			type: ["normal"],
			anal_shield: 0,
			set: "under_lower",
			gender: "n",
			warmth: 2,
			cost: 1500,
			description: "Protects the essentials. Just.",
			shop: ["clothing", "adult"],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			penis_img: 1,
			high_img: 0,
			cursed: 0,
			location: 0,
			iconFile: "g-string.png",
			accIcon: 0,
		},

		{
			index: 17,
			name: "crotchless panties",
			name_cap: "Crotchless panties",
			name_simple: "panties",
			variable: "crotchlesspanties",
			integrity: 50,
			integrity_max: 50,
			fabric_strength: 20,
			reveal: 900,
			rearresize: 0,
			word: "n",
			one_piece: 0,
			state: "waist",
			state_base: "waist",
			plural: 1,
			colour: 0,
			colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "pale tangerine", "teal", "pale white", "pale yellow", "custom"],
			colour_sidebar: 1,
			exposed: 1,
			exposed_base: 1,
			vagina_exposed: 1,
			vagina_exposed_base: 1,
			anus_exposed: 1,
			anus_exposed_base: 1,
			type: ["fetish", "naked"],
			anal_shield: 0,
			set: "under_lower",
			gender: "f",
			femininity: 300,
			warmth: 3,
			cost: 1200,
			description: "Open access.",
			shop: ["clothing", "adult"],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			penis_img: 0,
			high_img: 0,
			cursed: 0,
			location: 0,
			iconFile: "crotchless_panties.png",
			accIcon: 0,
		},

		{
			index: 18,
			name: "microkini bottom",
			name_cap: "Microkini bottom",
			name_simple: "swimsuit",
			variable: "microkini",
			integrity: 30,
			integrity_max: 30,
			fabric_strength: 20,
			reveal: 900,
			rearresize: 0,
			word: "a",
			one_piece: 0,
			state: "waist",
			state_base: "waist",
			plural: 0,
			colour: 0,
			colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "tangerine", "teal", "white", "yellow", "custom"],
			colour_sidebar: 1,
			exposed: 0,
			exposed_base: 0,
			vagina_exposed: 0,
			vagina_exposed_base: 0,
			anus_exposed: 0,
			anus_exposed_base: 0,
			type: ["swim"],
			anal_shield: 0,
			set: "under_lower",
			gender: "f",
			femininity: 300,
			warmth: 2,
			cost: 2400,
			description: "Skirts the borders of decency.",
			shop: ["clothing", "adult"],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			penis_img: 1,
			high_img: 0,
			cursed: 0,
			location: 0,
			iconFile: "microkini_bottom.png",
			accIcon: 0,
		},

		{
			index: 19,
			name: "speedo",
			name_cap: "Speedo",
			name_simple: "speedo",
			variable: "speedo",
			integrity: 50,
			integrity_max: 50,
			fabric_strength: 20,
			reveal: 700,
			rearresize: 0,
			word: "a",
			one_piece: 0,
			state: "waist",
			state_base: "waist",
			plural: 0,
			colour: 0,
			colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "tangerine", "teal", "white", "yellow", "custom"],
			colour_sidebar: 1,
			exposed: 0,
			exposed_base: 0,
			vagina_exposed: 0,
			vagina_exposed_base: 0,
			anus_exposed: 0,
			anus_exposed_base: 0,
			type: ["swim"],
			anal_shield: 0,
			set: "under_lower",
			gender: "m",
			femininity: -300,
			warmth: 5,
			cost: 2400,
			description: "Show what you've got. Without getting arrested.",
			shop: ["clothing"],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			penis_img: 1,
			high_img: 0,
			cursed: 0,
			location: 0,
			iconFile: "speedo.png",
			accIcon: 0,
		},

		{
			index: 20,
			name: "striped panties",
			name_cap: "Striped panties",
			name_simple: "panties",
			variable: "stripedpanties",
			integrity: 100,
			integrity_max: 100,
			fabric_strength: 15,
			reveal: 400,
			rearresize: 0,
			word: "n",
			one_piece: 0,
			state: "waist",
			state_base: "waist",
			plural: 1,
			colour: 0,
			colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "tangerine", "teal", "white", "yellow", "custom"],
			colour_sidebar: 1,
			exposed: 0,
			exposed_base: 0,
			vagina_exposed: 0,
			vagina_exposed_base: 0,
			anus_exposed: 0,
			anus_exposed_base: 0,
			type: ["normal"],
			anal_shield: 0,
			set: "under_lower",
			gender: "f",
			femininity: 300,
			warmth: 5,
			cost: 600,
			description: "Brimming with personality.",
			shop: ["clothing"],
			accessory: 1,
			accessory_colour: 0,
			accessory_colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "tangerine", "teal", "white", "yellow", "custom"],
			accessory_colour_sidebar: 1,
			penis_img: 1,
			high_img: 0,
			cursed: 0,
			location: 0,
			iconFile: "striped_panties.png",
			accIcon: "striped_panties_acc.png",
		},

		{
			index: 21,
			name: "loincloth",
			name_cap: "Loincloth",
			name_simple: "loincloth",
			variable: "loincloth",
			integrity: 80,
			integrity_max: 80,
			fabric_strength: 10,
			reveal: 800,
			rearresize: 0,
			word: "a",
			one_piece: 0,
			state: "waist",
			state_base: "waist",
			plural: 0,
			colour: 0,
			colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "tangerine", "teal", "custom"],
			colour_sidebar: 1,
			exposed: 0,
			exposed_base: 0,
			vagina_exposed: 1,
			vagina_exposed_base: 1,
			anus_exposed: 1,
			anus_exposed_base: 1,
			no_aside: 1,
			type: ["normal"],
			anal_shield: 0,
			set: "under_lower",
			gender: "n",
			warmth: 10,
			cost: 100,
			description: "Revealing, unprotective, sturdy, and savage.",
			shop: ["forest"],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			penis_img: 0,
			high_img: 0,
			cursed: 0,
			location: 0,
			iconFile: "loincloth.png",
			accIcon: 0,
		},

		{
			index: 22,
			name: "thong",
			name_cap: "Thong",
			name_simple: "thong",
			variable: "thong",
			integrity: 40,
			integrity_max: 40,
			fabric_strength: 20,
			reveal: 700,
			rearresize: 0,
			word: "a",
			one_piece: 0,
			state: "waist",
			state_base: "waist",
			plural: 0,
			colour: 0,
			colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "pale tangerine", "teal", "pale white", "pale yellow", "custom"],
			colour_sidebar: 1,
			exposed: 0,
			exposed_base: 0,
			vagina_exposed: 0,
			vagina_exposed_base: 0,
			anus_exposed: 1,
			anus_exposed_base: 1,
			type: ["normal"],
			anal_shield: 0,
			set: "under_lower",
			gender: "f",
			femininity: 300,
			warmth: 3,
			cost: 1500,
			description: "Protects the essentials. Just.",
			shop: ["clothing", "adult"],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			penis_img: 1,
			high_img: 0,
			cursed: 0,
			location: 0,
			iconFile: "thong.png",
			accIcon: 0,
		},

		{
			index: 23,
			name: "classic plain panties",
			name_cap: "Classic plain panties",
			name_simple: "panties",
			variable: "classicplainpanties",
			integrity: 100,
			integrity_max: 100,
			fabric_strength: 15,
			reveal: 400,
			rearresize: 0,
			word: "n",
			one_piece: 0,
			state: "waist",
			state_base: "waist",
			plural: 1,
			colour: 0,
			colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "tangerine", "teal", "white", "pale yellow", "custom"],
			colour_sidebar: 1,
			exposed: 0,
			exposed_base: 0,
			vagina_exposed: 0,
			vagina_exposed_base: 0,
			anus_exposed: 0,
			anus_exposed_base: 0,
			type: ["normal"],
			anal_shield: 0,
			set: "under_lower",
			gender: "f",
			femininity: 300,
			warmth: 10,
			cost: 500,
			description: "No-nonsense. Vintage.",
			shop: ["clothing"],
			shopGroup: "plainpanties",
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			penis_img: 0,
			high_img: 0,
			cursed: 0,
			location: 0,
			iconFile: "classic_plain_panties.png",
			accIcon: 0,
		},

		{
			index: 24,
			name: "classic bikini bottoms",
			name_cap: "Classic bikini bottoms",
			name_simple: "bikini bottoms",
			variable: "classicbikini",
			integrity: 20,
			integrity_max: 20,
			fabric_strength: 20,
			reveal: 700,
			rearresize: 0,
			word: "n",
			one_piece: 0,
			state: "waist",
			state_base: "waist",
			plural: 1,
			colour: 0,
			colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "tangerine", "teal", "white", "yellow", "custom"],
			colour_sidebar: 1,
			exposed: 0,
			exposed_base: 0,
			vagina_exposed: 0,
			vagina_exposed_base: 0,
			anus_exposed: 0,
			anus_exposed_base: 0,
			type: ["swim", "tanLines"],
			anal_shield: 0,
			set: "under_lower",
			gender: "f",
			femininity: 300,
			warmth: 10,
			cost: 2000,
			description: "Revealing swimwear. Vintage.",
			shop: ["clothing"],
			shopGroup: "bikinibottom",
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			penis_img: 0,
			high_img: 0,
			cursed: 0,
			location: 0,
			iconFile: "classic_bikini_bottoms.png",
			accIcon: 0,
		},

		{
			index: 25,
			name: "classic lace panties",
			name_cap: "Classic lace panties",
			name_simple: "panties",
			variable: "classiclacepanties",
			integrity: 60,
			integrity_max: 60,
			fabric_strength: 15,
			reveal: 600,
			rearresize: 0,
			word: "n",
			one_piece: 0,
			state: "waist",
			state_base: "waist",
			plural: 1,
			colour: 0,
			colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "tangerine", "teal", "white", "pale yellow", "custom"],
			colour_sidebar: 1,
			exposed: 0,
			exposed_base: 0,
			vagina_exposed: 0,
			vagina_exposed_base: 0,
			anus_exposed: 0,
			anus_exposed_base: 0,
			type: ["normal"],
			anal_shield: 0,
			set: "under_lower",
			gender: "f",
			femininity: 300,
			warmth: 8,
			cost: 1500,
			description: "Fashionable and sexy. Vintage.",
			shop: ["clothing"],
			shopGroup: "lacepanties",
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			penis_img: 0,
			high_img: 0,
			cursed: 0,
			location: 0,
			iconFile: "classic_lace_panties.png",
			accIcon: 0,
		},

		{
			index: 26,
			name: "classic briefs",
			name_cap: "Classic briefs",
			name_simple: "undies",
			variable: "classicbriefs",
			integrity: 100,
			integrity_max: 100,
			fabric_strength: 15,
			reveal: 400,
			rearresize: 0,
			word: "n",
			one_piece: 0,
			state: "waist",
			state_base: "waist",
			plural: 1,
			colour: 0,
			colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "tangerine", "teal", "white", "pale yellow", "custom"],
			colour_sidebar: 1,
			exposed: 0,
			exposed_base: 0,
			vagina_exposed: 0,
			vagina_exposed_base: 0,
			anus_exposed: 0,
			anus_exposed_base: 0,
			no_aside: 1,
			type: ["normal"],
			anal_shield: 0,
			set: "under_lower",
			gender: "m",
			femininity: -300,
			warmth: 10,
			cost: 500,
			description: "Snug and vintage.",
			shop: ["clothing"],
			shopGroup: "briefs",
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			penis_img: 0,
			high_img: 0,
			cursed: 0,
			location: 0,
			iconFile: "classic_briefs.png",
			accIcon: 0,
		},

		{
			index: 27,
			name: "classic school swimsuit bottom",
			name_cap: "Classic school swimsuit bottom",
			name_simple: "swimsuit",
			variable: "classicschoolswimsuit",
			integrity: 40,
			integrity_max: 40,
			fabric_strength: 20,
			reveal: 600,
			rearresize: 0,
			word: "a",
			one_piece: 1,
			state: "waist",
			state_base: "waist",
			plural: 0,
			colour: 0,
			colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "tangerine", "teal", "white", "yellow", "custom"],
			colour_sidebar: 1,
			exposed: 0,
			exposed_base: 0,
			vagina_exposed: 0,
			vagina_exposed_base: 0,
			anus_exposed: 0,
			anus_exposed_base: 0,
			type: ["swim", "school", "tanLines"],
			anal_shield: 0,
			set: "classic school swimsuit",
			warmth: 10,
			gender: "f",
			femininity: 300,
			cost: 0,
			description: "Proper school swimwear. Vintage.",
			shop: ["clothing"],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			penis_img: 0,
			high_img: 0,
			cursed: 0,
			location: 0,
			iconFile: 0,
			accIcon: 0,
			outfitSecondary: ["under_upper", "classic school swimsuit"],
		},

		{
			index: 28,
			name: "jockstrap",
			name_cap: "Jockstrap",
			name_simple: "jockstrap",
			variable: "jockstrap",
			integrity: 120,
			integrity_max: 120,
			fabric_strength: 20,
			reveal: 700,
			rearresize: 0,
			word: "a",
			one_piece: 0,
			state: "waist",
			state_base: "waist",
			plural: 0,
			colour: 0,
			colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "tangerine", "teal", "white", "yellow", "custom"],
			colour_sidebar: 1,
			exposed: 0,
			exposed_base: 0,
			vagina_exposed: 0,
			vagina_exposed_base: 0,
			anus_exposed: 1,
			anus_exposed_base: 1,
			type: ["normal"],
			anal_shield: 0,
			set: "under_lower",
			warmth: 10,
			gender: "m",
			femininity: -200,
			cost: 3500,
			description: "Not too tight.",
			shop: ["clothing"],
			accessory: 1,
			accessory_colour: 0,
			accessory_colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "tangerine", "teal", "white", "yellow", "custom"],
			accessory_colour_sidebar: 1,
			penis_img: 0,
			high_img: 0,
			cursed: 0,
			location: 0,
			iconFile: "jockstrap.png",
			accIcon: "jockstrap_acc.png",
		},

		{
			index: 29,
			name: "boxers",
			name_cap: "Boxers",
			name_simple: "undies",
			variable: "boxers",
			integrity: 100,
			integrity_max: 100,
			fabric_strength: 20,
			reveal: 350,
			rearresize: 0,
			word: "n",
			one_piece: 0,
			state: "waist",
			state_base: "waist",
			plural: 1,
			colour: 0,
			colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "tangerine", "teal", "white", "yellow", "custom"],
			colour_sidebar: 1,
			exposed: 0,
			exposed_base: 0,
			vagina_exposed: 0,
			vagina_exposed_base: 0,
			anus_exposed: 0,
			anus_exposed_base: 0,
			no_aside: 1,
			type: ["normal"],
			anal_shield: 0,
			set: "under_lower",
			warmth: 10,
			gender: "m",
			femininity: -200,
			cost: 800,
			description: "Gives room to breathe.",
			shop: ["clothing", "school"],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			penis_img: 0,
			high_img: 0,
			cursed: 0,
			location: 0,
			iconFile: "boxers.png",
			accIcon: 0,
		},

		{
			index: 30,
			name: "long johns",
			name_cap: "Long johns",
			name_simple: "long johns",
			variable: "longjohns",
			integrity: 150,
			integrity_max: 150,
			fabric_strength: 20,
			reveal: 200,
			rearresize: 0,
			word: "n",
			one_piece: 0,
			state: "waist",
			state_base: "waist",
			plural: 1,
			colour: 0,
			colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "tangerine", "teal", "white", "yellow", "custom"],
			colour_sidebar: 1,
			exposed: 0,
			exposed_base: 0,
			vagina_exposed: 0,
			vagina_exposed_base: 0,
			anus_exposed: 0,
			anus_exposed_base: 0,
			no_aside: 1,
			type: ["normal"],
			anal_shield: 0,
			set: "under_lower",
			warmth: 30,
			gender: "m",
			femininity: -100,
			cost: 2500,
			description: "Helps keep the chill off.",
			shop: ["clothing"],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			penis_img: 0,
			high_img: 0,
			cursed: 0,
			location: 0,
			iconFile: "long_johns.png",
			accIcon: 0,
		},

		{
			index: 31,
			name: "school swim bottoms",
			name_cap: "School swim bottoms",
			name_simple: "swimsuit bottoms",
			variable: "schoolswimbottoms",
			integrity: 70,
			integrity_max: 70,
			fabric_strength: 20,
			reveal: 700,
			rearresize: 0,
			word: "n",
			one_piece: 0,
			state: "waist",
			state_base: "waist",
			plural: 1,
			colour: 0,
			colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "tangerine", "teal", "pale white", "pale yellow", "custom"],
			colour_sidebar: 1,
			exposed: 0,
			exposed_base: 0,
			vagina_exposed: 0,
			vagina_exposed_base: 0,
			anus_exposed: 0,
			anus_exposed_base: 0,
			type: ["swim", "school"],
			anal_shield: 0,
			set: "under_lower",
			warmth: 10,
			gender: "f",
			femininity: 300,
			cost: 3000,
			description: "Surprisingly scanty for sanctioned uniform.",
			shop: ["clothing", "school"],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			penis_img: 0,
			high_img: 0,
			cursed: 0,
			location: 0,
			iconFile: "school_swim_bottoms.png",
			accIcon: 0,
		},

		{
			index: 32,
			name: "cow panties",
			name_cap: "Cow panties",
			name_simple: "panties",
			variable: "cow",
			integrity: 100,
			integrity_max: 100,
			fabric_strength: 15,
			reveal: 500,
			rearresize: 0,
			word: "n",
			one_piece: 0,
			state: "waist",
			state_base: "waist",
			plural: 1,
			colour: 0,
			colour_options: [],
			exposed: 0,
			exposed_base: 0,
			vagina_exposed: 0,
			vagina_exposed_base: 0,
			anus_exposed: 0,
			anus_exposed_base: 0,
			type: ["costume"],
			anal_shield: 0,
			set: "under_lower",
			gender: "n",
			femininity: 0,
			warmth: 5,
			cost: 2000,
			description: "Cute cow print.",
			shop: ["forest"],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			penis_img: 0,
			high_img: 0,
			cursed: 0,
			location: 0,
			iconFile: "cow_panties.png",
			accIcon: 0,
		},

		{
			index: 33,
			name: "strap-on",
			name_cap: "Strap-on",
			name_simple: "strap-on",
			variable: "straponlower",
			integrity: 2000,
			integrity_max: 2000,
			fabric_strength: 30,
			reveal: 1000,
			word: "a",
			one_piece: 0,
			state: "waist",
			state_base: "waist",
			plural: 0,
			colour: 0,
			colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "white", "yellow", "tan", "fleshy"],
			colour_sidebar: 1,
			colour_combat: 0,
			exposed: 1,
			exposed_base: 1,
			vagina_exposed: 1,
			vagina_exposed_base: 1,
			anus_exposed: 1,
			anus_exposed_base: 1,
			type: ["strap-on", "fetish", "naked"],
			anal_shield: 0,
			set: "under_lower",
			gender: "f",
			warmth: 0,
			cost: 8000,
			description: "Worn on your hips. Used for penetrative sex.",
			shop: [],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			penis_img: 0,
			high_img: 0,
			cursed: 0,
			location: 0,
			hideUnderLower: ["leotard bottom", "unitard bottom"],
			iconFile: "strap-on.png",
			accIcon: 0,
			size: 2,
		},

		{
			index: 34,
			name: "strap-on horse cock",
			name_cap: "Strap-on horse cock",
			name_simple: "strap-on",
			variable: "straponhorse",
			integrity: 2000,
			integrity_max: 2000,
			fabric_strength: 30,
			reveal: 1000,
			word: "a",
			one_piece: 0,
			state: "waist",
			state_base: "waist",
			plural: 0,
			colour: 0,
			colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "white", "yellow", "tan", "fleshy"],
			colour_sidebar: 1,
			colour_combat: 0,
			exposed: 1,
			exposed_base: 1,
			vagina_exposed: 1,
			vagina_exposed_base: 1,
			anus_exposed: 1,
			anus_exposed_base: 1,
			type: ["strap-on", "fetish", "naked"],
			anal_shield: 0,
			set: "under_lower",
			gender: "f",
			warmth: 0,
			cost: 8000,
			description: "Novelty equine phallus. Worn on your hips. Used for penetrative sex.",
			shop: [],
			accessory: 1,
			accessory_colour: 0,
			accessory_colour_options: [],
			penis_img: 0,
			high_img: 0,
			cursed: 0,
			location: 0,
			hideUnderLower: ["leotard bottom", "unitard bottom"],
			iconFile: "strap-on_horse_cock.png",
			accIcon: 0,
			size: 4,
		},

		{
			index: 35,
			name: "strap-on knotted cock",
			name_cap: "Strap-on knotted cock",
			name_simple: "strap-on",
			variable: "straponknotted",
			integrity: 2000,
			integrity_max: 2000,
			fabric_strength: 30,
			reveal: 1000,
			word: "a",
			one_piece: 0,
			state: "waist",
			state_base: "waist",
			plural: 0,
			colour: 0,
			colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "white", "yellow", "tan", "fleshy"],
			colour_sidebar: 1,
			colour_combat: 0,
			exposed: 1,
			exposed_base: 1,
			vagina_exposed: 1,
			vagina_exposed_base: 1,
			anus_exposed: 1,
			anus_exposed_base: 1,
			type: ["strap-on", "fetish", "naked"],
			anal_shield: 0,
			set: "under_lower",
			gender: "f",
			warmth: 0,
			cost: 8000,
			description: "Novelty canine phallus. Worn on your hips. Used for penetrative sex.",
			shop: [],
			accessory: 1,
			accessory_colour: 0,
			accessory_colour_options: [],
			penis_img: 0,
			high_img: 0,
			cursed: 0,
			location: 0,
			hideUnderLower: ["leotard bottom", "unitard bottom"],
			iconFile: "strap-on_knotted_cock.png",
			accIcon: 0,
			size: 3,
		},

		{
			index: 36,
			name: "strap-on studded cock",
			name_cap: "Strap-on studded cock",
			name_simple: "strap-on",
			variable: "straponstudded",
			integrity: 2000,
			integrity_max: 2000,
			fabric_strength: 30,
			reveal: 1000,
			word: "a",
			one_piece: 0,
			state: "waist",
			state_base: "waist",
			plural: 0,
			colour: 0,
			colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "white", "yellow", "tan", "fleshy"],
			colour_sidebar: 1,
			colour_combat: 0,
			exposed: 1,
			exposed_base: 1,
			vagina_exposed: 1,
			vagina_exposed_base: 1,
			anus_exposed: 1,
			anus_exposed_base: 1,
			type: ["strap-on", "fetish", "naked"],
			anal_shield: 0,
			set: "under_lower",
			gender: "f",
			warmth: 0,
			cost: 8000,
			description: "Worn on your hips. Used for penetrative sex.",
			shop: [],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			penis_img: 0,
			high_img: 0,
			cursed: 0,
			location: 0,
			hideUnderLower: ["leotard bottom", "unitard bottom"],
			iconFile: "strap-on.png",
			accIcon: 0,
			size: 3,
		},

		{
			index: 37,
			name: "see-through swim bottoms",
			name_cap: "See-through swim bottoms",
			name_simple: "swimsuit bottoms",
			variable: "seethroughswimsuit",
			integrity: 60,
			integrity_max: 60,
			fabric_strength: 30,
			reveal: 800,
			rearresize: 0,
			word: "n",
			one_piece: 0,
			state: "waist",
			state_base: "waist",
			plural: 1,
			colour: 0,
			colour_options: ["black", "blue steel", "grey", "light pink", "light blue", "light green", "red", "pink", "purple", "tangerine", "teal", "custom"],
			colour_sidebar: 1,
			exposed: 0,
			exposed_base: 0,
			vagina_exposed: 0,
			vagina_exposed_base: 0,
			anus_exposed: 0,
			anus_exposed_base: 0,
			no_aside: 0,
			type: ["swim"],
			anal_shield: 0,
			set: "see-through swimsuit",
			warmth: 5,
			gender: "f",
			femininity: 300,
			cost: 3000,
			description: "Frames your torso.",
			shop: ["adult"],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			penis_img: 0,
			high_img: 0,
			cursed: 0,
			location: 0,
			iconFile: 0,
			accIcon: 0,
			outfitSecondary: ["under_upper", "see-through swimsuit"],
		},

		{
			index: 38,
			name: "shibari ropes bottom",
			name_cap: "Shibari ropes bottom",
			name_simple: "bondage ropes",
			variable: "shibari",
			integrity: 200,
			integrity_max: 200,
			fabric_strength: 30,
			reveal: 600,
			rearresize: 0,
			word: "a",
			one_piece: 1,
			state: "waist",
			state_base: "waist",
			plural: 1,
			colour: 0,
			colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "tangerine", "teal", "white", "yellow", "custom"],
			colour_sidebar: 1,
			colour_combat: "black",
			exposed: 1,
			exposed_base: 1,
			vagina_exposed: 1,
			vagina_exposed_base: 1,
			anus_exposed: 1,
			anus_exposed_base: 1,
			type: ["fetish", "naked"],
			anal_shield: 0,
			set: "shibari",
			gender: "n",
			warmth: 10,
			cost: 0,
			description: "For those into rope play.",
			shop: ["adult"],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			penis_img: 0,
			high_img: 0,
			cursed: 0,
			location: 0,
			iconFile: "shibari_ropes.png",
			accIcon: 0,
			outfitSecondary: ["under_upper", "shibari ropes"],
		},

		{
			index: 39,
			name: "highwaisted microkini bottom",
			name_cap: "Highwaisted microkini bottom",
			name_simple: "swimsuit",
			variable: "highmicrokini",
			integrity: 30,
			integrity_max: 30,
			fabric_strength: 20,
			reveal: 900,
			rearresize: 0,
			word: "a",
			one_piece: 0,
			state: "waist",
			state_base: "waist",
			plural: 0,
			colour: 0,
			colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "tangerine", "teal", "white", "yellow", "custom"],
			colour_sidebar: 1,
			colour_combat: 0,
			exposed: 0,
			exposed_base: 0,
			vagina_exposed: 0,
			vagina_exposed_base: 0,
			anus_exposed: 0,
			anus_exposed_base: 0,
			type: ["swim"],
			anal_shield: 0,
			set: "under_lower",
			gender: "f",
			femininity: 300,
			warmth: 2,
			cost: 2400,
			description: "Skirts the borders of decency.",
			shop: ["clothing", "adult"],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			penis_img: 1,
			high_img: 0,
			cursed: 0,
			location: 0,
			iconFile: "high_microkini_bottom.png",
			accIcon: 0,
		},

		{
			index: 40,
			name: "turtleneck leotard bottom",
			name_cap: "Turtleneck leotard bottom",
			name_simple: "leotard",
			variable: "leotardturtleneck",
			integrity: 100,
			integrity_max: 100,
			fabric_strength: 20,
			reveal: 600,
			rearresize: 0,
			word: "a",
			one_piece: 1,
			state: "waist",
			state_base: "waist",
			plural: 0,
			colour: 0,
			colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "tangerine", "teal", "white", "yellow", "custom"],
			colour_sidebar: 1,
			colour_combat: 0,
			exposed: 0,
			exposed_base: 0,
			vagina_exposed: 0,
			vagina_exposed_base: 0,
			anus_exposed: 0,
			anus_exposed_base: 0,
			no_aside: 1,
			type: ["dance", "athletic"],
			anal_shield: 0,
			set: "turtleneck leotard",
			gender: "n",
			warmth: 20,
			cost: 0,
			description: "Form fitting.",
			shop: ["clothing", "adult"],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			penis_img: 1,
			high_img: 0,
			cursed: 0,
			location: 0,
			iconFile: 0,
			accIcon: 0,
			outfitSecondary: ["under_upper", "turtleneck leotard"],
		},

		{
			index: 41,
			name: "tie side bikini bottoms",
			name_cap: "Tie side bikini bottoms",
			name_simple: "bikini bottoms",
			variable: "tiesidebikini",
			integrity: 15,
			integrity_max: 15,
			fabric_strength: 20,
			reveal: 800,
			rearresize: 0,
			word: "n",
			one_piece: 0,
			state: "waist",
			state_base: "waist",
			plural: 1,
			colour: 0,
			colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "tangerine", "teal", "white", "yellow", "custom"],
			colour_sidebar: 1,
			exposed: 0,
			exposed_base: 0,
			vagina_exposed: 0,
			vagina_exposed_base: 0,
			anus_exposed: 0,
			anus_exposed_base: 0,
			type: ["swim", "tanLines"],
			anal_shield: 0,
			set: "under_lower",
			gender: "f",
			femininity: 300,
			warmth: 5,
			cost: 2000,
			description: "Revealing swimwear.",
			shop: ["clothing"],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			penis_img: 1,
			high_img: 0,
			cursed: 0,
			location: 0,
			iconFile: "tieside_bikini_bottoms.png",
			accIcon: 0,
		},

		{
			index: 42,
			name: "vintage lace panties",
			name_cap: "Vintage lace panties",
			name_simple: "panties",
			variable: "lacepantiesold",
			integrity: 60,
			integrity_max: 60,
			fabric_strength: 15,
			reveal: 600,
			rearresize: 0,
			word: "n",
			one_piece: 0,
			state: "waist",
			state_base: "waist",
			plural: 1,
			colour: 0,
			colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "pale tangerine", "teal", "pale white", "pale yellow", "custom"],
			colour_sidebar: 1,
			exposed: 0,
			exposed_base: 0,
			vagina_exposed: 0,
			vagina_exposed_base: 0,
			anus_exposed: 0,
			anus_exposed_base: 0,
			type: ["normal"],
			anal_shield: 0,
			set: "under_lower",
			gender: "f",
			femininity: 300,
			warmth: 5,
			cost: 1500,
			description: "Fashionable and sexy.",
			shop: ["clothing", "adult"],
			shopGroup: "lacepanties",
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			penis_img: 0,
			high_img: 0,
			cursed: 0,
			location: 0,
			iconFile: "lace_panties.png",
			accIcon: 0,
		},
	];

	/*
		Clothes that modders add go into this array, this should be empty in the base game at all times.
		These items should have a `modder` variable with a the modders name in a short string
	*/
	setup.moddedClothes.under_lower = [];
	/* 北极星模组 */
	setup.moddedClothes.under_lower = setup.moddedClothes.under_lower.concat([
	{
		name: "tentacle bottom",
		name_cap: "Tentacle suit bottom",cn_name_cap: "触手套装下装",
		variable: "tentacle",
		integrity: 70000,
		integrity_max: 70000,
		fabric_strength: 70000,
		reveal: 700,
		rearresize: 0,
		word: "a",
		one_piece: 1,
		state: "waist",
		state_base: "waist",
		plural: 1,
		colour: 0,
		colour_options: [],
		colour_sidebar: 1,
		colour_combat:"black",
		exposed: 0,
		exposed_base: 0,
		vagina_exposed: 0,
		vagina_exposed_base: 0,
		anus_exposed: 0,
		anus_exposed_base: 0,
		type: ["fetish", "swim", "school"],
		anal_shield: 0,
		set: "tentacle",
		gender: "f",
		femininity: 300,
		warmth: 40,
		cost: 0,
		description: "触手组成的服装。",
		shop: [],
		accessory: 0,
		accessory_colour: 0,
		accessory_colour_options: [],
		penis_img: 0,
		high_img: 0,
		cursed: 1,
		location: 0,
		iconFile: "",
		accIcon: 0,
		outfitSecondary: ["under_upper","tentacle top"]
	},
	{
		name: "mushroom bottoms",
		name_cap: "Mushroom bottoms",cn_name_cap: "蘑菇内裤",
		variable: "mushroom2",
		integrity: 100,
		integrity_max: 100,
		fabric_strength: 20,
		reveal: 400,
		rearresize: 0,
		word: "n",
		one_piece: 0,
		state: "waist",
		state_base: "waist",
		plural: 1,
		colour: 0,
		colour_options: [],
		colour_sidebar: 1,
		exposed: 0,
		exposed_base: 0,
		vagina_exposed: 0,
		vagina_exposed_base: 0,
		anus_exposed: 0,
		anus_exposed_base: 0,
		no_aside: 1,
		type: ["rainproof"],
		anal_shield: 0,
		set: "mushroom",
		gender: "m",
		femininity: -300,
		warmth: 10,
		cost: 500,
		description: "天然无化肥。",
		shop: [],
		accessory: 1,
		accessory_colour: 0,
		accessory_colour_options: [],
		accessory_colour_combat:"",
		penis_img: 0,
		high_img: 0,
		cursed: 0,
		location: 0,
		iconFile: "",
		accIcon: 0,
		
	},
	]);
	/* 北极星 */

	setup.moddedClothes.under_lower.forEach((x, i) => (x.index = setup.clothes.under_lower.length + i));
	setup.clothes.under_lower.push(...setup.moddedClothes.under_lower);
}
window.initUnderLower = initUnderLower;
